const Project = require('../../models/launchpad/project');

class LaunchpadController {

    static step1(req,res,next) {
        let user = req.decoded.id;
        let { 
            full_name, 
            email, 
            position, 
            other_position, 
            pitch, 
            regulated, 
            other_regulated, 
            nda_signed, 
            legal_opinion_document,
            project_name, 
            coin_full_name, 
            coin_symbol, 
            official_website, 
            permanent_link,
            nature_project,
            other_nature_project,
            main_application,
            target_industry,
            project_target,
            brief_project_history,
            accrue_native_digital_asset,
            long_term_vision,
            quarterly_project_roadmap,
            current_development,
            native_digital_necessary,
            comprehensive_description,
            limit_number_token_held,
            existing_platform,differentiate_project,
            how_many_users, 
            social_communities,
            developer_communities,
            level_development, 
            product_demos, 
            users_intended_purpose, 
            applicable_feature, 
            other_applicable_feature,  
            associated_with_token,
            smart_contract_underlying,
            is_open_source,
            other_is_open_source,
            open_source_documentation,
            github,
            team_member,
            team_member_not_fulltime,
            team_members_involved,
            all_projects_currently,
            project_advistors,
            identifies_each_member,
            fundraising, 
            chart_detailing, 
            owned_by_members,
             multiple_private, 
             anticipated_codeo, 
             expected_public,
             total_supply,
             conversion_price,
             countries_excluded
        } = req.body;
            Project.create({
                full_name, 
                email, 
                position, 
                other_position, 
                pitch, 
                regulated, 
                other_regulated, 
                nda_signed, 
                legal_opinion_document,
                project_name, 
                coin_full_name, 
                coin_symbol, 
                official_website, 
                permanent_link,
                nature_project,
                other_nature_project,
                main_application,
                target_industry,
                project_target,
                brief_project_history,
                accrue_native_digital_asset,
                long_term_vision,
                quarterly_project_roadmap,
                current_development,
                native_digital_necessary,
                comprehensive_description,
                limit_number_token_held,
                existing_platform,differentiate_project,
                how_many_users, 
                social_communities,
                developer_communities,
                level_development, 
                product_demos, 
                users_intended_purpose, 
                applicable_feature, 
                other_applicable_feature,  
                associated_with_token,
                smart_contract_underlying,
                is_open_source,
                other_is_open_source,
                open_source_documentation,
                github,
                team_member,
                team_member_not_fulltime,
                team_members_involved,
                all_projects_currently,
                project_advistors,
                identifies_each_member,
                fundraising, 
                chart_detailing, 
                owned_by_members,
                 multiple_private, 
                 anticipated_codeo, 
                 expected_public,
                 total_supply,
                 conversion_price,
                 countries_excluded
            })
            .then(project => {
                res.status(202).json({project, status: 202})
            })
            .catch(next);
    };

};

module.exports = LaunchpadController;